// <auto-generated />
namespace PocketArtCollection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ueml1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ueml1));
        
        string IMigrationMetadata.Id
        {
            get { return "201701140038043_ueml1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
